### ISSUE TITLE
models: redundant code

### ISSUE THREAD

**Issue by malor** [greatehop/serversmanagement#5]
Code here https://github.com/greatehop/serversmanagement/blob/master/app/models.py#L59-L62 :

``` python

        if server_id is not None:
            self.server_id = server_id
        if cmd_out is not None:
            self.cmd_out = cmd_out

```

makes little sense as both `server_id` and `cmd_out` columns already default to `None`, if not set to some other values.

Overall models accept keyword arguments in `__init__()` by default, so you must not need to override it for such simple cases.

``` python

r = Run(server_id=1, cmd_out='test')

```

would work.

**Comment by greatehop** [comment]
Oops, thanks!
